### ISSUE TITLE
Test fail with "Error, Variable: 'LinearClosure' must have a value"

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/ZXCalculusForCAP#18]
https://github.com/homalg-project/ZXCalculusForCAP/actions/runs/6820681034/job/18549972712

I assume this is due to https://github.com/homalg-project/CategoricalTowers/pull/415, because nothing else seems to have changed. @mohamed-barakat @kamalsaleh Is this expected? That PR does not seem to change any dependencies, so I do not understand how this error might arise.

**Comment by kamalsaleh** [comment]
linear closures are read in `FreydCategoriesForCAP` only if `FinSetsForCAP` is loaded. Hence, the above PR.
